### ISSUE TITLE
tensorflow train_cifar10.py very slow

### ISSUE THREAD

**Issue by WeitaoVan** [CuriousAI/mean-teacher#1]
Thanks for your inspiring idea and the corresponding code.

I try to run the tensorflow code train_cifar10.py.
But it takes more than 2 hours to construct the computational graph and I'm still stuck here.
The screen does not print any thing.
If I replace the CNNs in the original code with a plain ResNet-32 (without Weight Normalization or other tricks), the whole code goes on well.

Do you know what might be wrong?

Thanks.

**Comment by tarvaina** [comment]
Hi and thanks for the comment.

Which TF version are you using? The newest version seems to hang up in the way you describe. TF 1.2.1 should work. 

I think the issue is in either weight norm or ema model code or maybe their combination. Unfortunately I haven’t had time to hunt it down. PRs welcome if you figure it out.

**Comment by WeitaoVan** [comment]
I changed to TF 1.2.1. Now it works fine.
Thank you!

**Comment by tarvaina** [comment]
Nice! Thanks for your comment.

**Comment by tarvaina** [comment]
See the discussion in pull request #5. This is related to the data-dependent initialization of weight-normalized layers.

Smart variable initialization appears to be broken in TensorFlow since 1.3, and may get fixed in the next release. Here's the currently active bug report in TensorFlow issues: [TensorFlow variable initializers broken #13351](https://github.com/tensorflow/tensorflow/issues/13351). As a possible workaround, here's a smarter initialization scheme from OpenAI: [smart_initialize.py](https://gist.github.com/yaroslavvb/d592394c0cedd32513f8fbb87ca05938).

**Comment by liuajian** [comment]
your python --version?  @WeitaoVan

**Comment by liuajian** [comment]
I can not download the tf1.2.x with python3.x

**Comment by tarvaina** [comment]
I think I used both Python 3.5 and 3.6 in the development of this, and TF 1.2.x.

**Comment by LuJyKa** [comment]
On Tensorflow 1.8, I found a workaround:
There is a process to ensure no cycle dependencies, but cost a lot of time.

Comment the line 851&852 around in pyfolder/Lib/site-packages/tensorflow/python/ops/variables.py:
```
    def has_cycle(op, path):
      """Detect cycles in the dependencies of `initial_value`."""
      if op.name in path:
        return True
      path.add(op.name)
      for op_input in op.inputs:
        if has_cycle(op_input.op, path):
          return True
      for op_control_input in op.control_inputs:
        if has_cycle(op_control_input, path):
          return True
      path.remove(op.name)
      return False
    # if has_cycle(initial_value.op, path=set()):  # <--- comment this
    #   return initial_value  # <--- comment this

    return self._safe_initial_value_from_tensor(initial_value, op_cache={})
```

**Comment by liangzimei** [comment]
when i use tf 1.2, run train-cifar10.py ,there is an error:
`
Traceback (most recent call last):
  File "train_cifar10.py", line 52, in <module>
    run()
  File "train_cifar10.py", line 33, in run
    model = Model(RunContext(__file__, 0))
  File "/host/zhang/DL/SSL/mean-teacher/tensorflow/mean_teacher/model.py", line 126, in __init__
    num_logits=self.hyper['num_logits'])
  File "/host/zhang/DL/SSL/mean-teacher/tensorflow/mean_teacher/model.py", line 346, in inference
    _ = tower(**tower_args, dropout_probability=student_dropout_probability, is_initialization=True)
  File "/host/zhang/DL/SSL/mean-teacher/tensorflow/mean_teacher/model.py", line 410, in tower
    net = slim.dropout(net, 1 - dropout_probability, scope='dropout_probability_1')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1214, in dropout
    _scope=sc)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/core.py", line 247, in __init__
    self.rate = min(1., max(0., rate))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 564, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
`

it seems a bug of tf 1.2, see [here](https://github.com/tensorflow/tensorflow/issues/11005), they suggest to try tf1.3, but 1.3 will hang up in the beginning.  so is there any way to run the code?

**Comment by liangzimei** [comment]
tf 1.2.0  has a bug using dropout , see  [here](https://github.com/tensorflow/tensorflow/issues/11005) . tf 1.2.1 is ok.

**Comment by rajneo** [comment]
Tried running svhn.py. 
No output shown for atleast 2hrs.
Using tensorflow 1.2.1

Do you know what might be wrong

**Comment by Xiaotian0726** [comment]
> I can not download the tf1.2.x with python3.x

Tensorflow 1.x is not available for python 3.8, use python 3.5 and 3.6 instead. See more at issue #39768 of tensorflow
