### ISSUE TITLE
Cannot start training in cifar10 because of incorrect filesname

### ISSUE THREAD

**Issue by kurobaneHITOMI** [CuriousAI/mean-teacher#34]
Hi,sir. When I use `python train_cifar10.py` it seems not work and report as below:

Traceback (most recent call last):
  File "train_cifar10.py", line 51, in <module>
    run()
  File "train_cifar10.py", line 32, in run
    model = Model(RunContext(__file__, 0))
  File "D:\github\git - mean-teacher-master\tensorflow\experiments\run_context.p
y", line 65, in __init__
    os.makedirs(self.result_dir)
  File "d:\ANACONDA3\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "d:\ANACONDA3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'results/train_cifar10
/2019-04-09_17:52:46'

Chinese here means 'incorrect files name, directory name, or volume label method'
It's python 3.6 and tensorflow 1.2.1 here.
I try to download cifar10 dataset by myself and modify prepare_data.sh but get the same error.
What shall I do sir?

**Comment by kurobaneHITOMI** [comment]
I see ,sir. In windows the filesname cannot include':' but in `run_context.py` the path created includes it, so it doesn't work.
But now there's another question here, `preprocess_cifar10.py` seems not work well, as failed to create "cifar10_gcn_zca_v2.npz". When I use `prepare_data.sh` till `preprocess_cifar10` it closes immediately. what's wrong here?

**Comment by kurobaneHITOMI** [comment]
That's the error when I run `python preprocess_cifar10.py` independently:

Traceback (most recent call last):
  File "preprocess_cifar10.py", line 97, in <module>
    do()
  File "preprocess_cifar10.py", line 84, in do
    train_x_orig, train_y = cifar10_orig_train()
  File "preprocess_cifar10.py", line 27, in cifar10_orig_train
    return load_batch_files([os.path.join(DIR, "data_batch_{}.mat".format(i)) fo
r i in range(1, 6)])
  File "preprocess_cifar10.py", line 35, in load_batch_files
    data_batches, label_batches = zip(*[load_batch_file(batch_file) for batch_fi
le in batch_files])
  File "preprocess_cifar10.py", line 35, in <listcomp>
    data_batches, label_batches = zip(*[load_batch_file(batch_file) for batch_fi
le in batch_files])
  File "preprocess_cifar10.py", line 42, in load_batch_file
    d = loadmat(path)
  File "d:\ANACONDA3\lib\site-packages\scipy\io\matlab\mio.py", line 141, in loa
dmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "d:\ANACONDA3\lib\site-packages\scipy\io\matlab\mio.py", line 64, in mat_
reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

**Comment by kurobaneHITOMI** [comment]
Emmmm I have solved it by upgrade matlab package, and now it works well.
