### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'to_msgpack'

### ISSUE THREAD

**Issue by BolinLi-s** [CuriousAI/mean-teacher#40]
Traceback (most recent call last):
  File "main.py", line 423, in <module>
    main(RunContext(__file__, 0))
  File "main.py", line 104, in main
    train(train_loader, model, ema_model, optimizer, epoch, training_log)
  File "main.py", line 310, in train
    **meters.sums()
  File "/home/lbl/work/mean-teacher-master/pytorch/mean_teacher/run_context.py", line 34, in record
    self._record(step, col_val_dict)
  File "/home/lbl/work/mean-teacher-master/pytorch/mean_teacher/run_context.py", line 45, in _record
    self.save()
  File "/home/lbl/work/mean-teacher-master/pytorch/mean_teacher/run_context.py", line 38, in save
    df.to_msgpack(self.log_file_path, compress='zlib')
  File "/home/lbl/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_msgpack'

my pandas version is 1.0.1 and this function may be removed earlier, so what can i do?

**Comment by Wangzheaos** [comment]
更换版本pandas==0.20.3

**Comment by chouqin3** [comment]
> 更换版本pandas==0.20.3

no work

**Comment by yanghu819** [comment]
same problem+1
